# Generated by Django 4.2.3 on 2023-07-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_todoitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
